let stockProductos = [
    {id: 1, nombre: "Cuadro 1", tipo: "cuadro", cantidad: 1, desc: "Un palacio diferente", precio: 1200, tamaño: "2x3", img: './img/palacio.jpg'},
    {id: 2, nombre: "Cuadro 2", tipo: "cuadro", cantidad: 1, desc: "Un palacio diferente", precio: 1100, tamaño: "2x3", img: './img/palacio.jpg'},
    {id: 3, nombre: "Cuadro 3", tipo: "cuadro", cantidad: 1, desc: "Un palacio diferente", precio: 1200, tamaño: "4x3", img: './img/palacio.jpg'},
    {id: 4, nombre: "Cuadro 4", tipo: "cuadro", cantidad: 1, desc: "Un palacio diferente", precio: 1400, tamaño: "4x3", img: './img/palacio.jpg'},
    {id: 5, nombre: "Cuadro 5", tipo: "cuadro", cantidad: 1, desc: "Un palacio diferente", precio: 1200, tamaño: "2x3", img: './img/palacio.jpg'},
    {id: 6, nombre: "Cuadro 6", tipo: "cuadro", cantidad: 1, desc: "Un palacio diferente", precio: 1500, tamaño: "2x3", img: './img/palacio.jpg'},
    {id: 7, nombre: "Muro 1", tipo: "muro", cantidad: 1, desc: "east side Berlin", precio: 500, tamaño: "1x1", img: './img/muro.jpg'},
    {id: 8, nombre: "Muro 2", tipo: "muro", cantidad: 1, desc: "east side Berlin", precio: 500, tamaño: "1x1", img: './img/muro.jpg'},
    {id: 9, nombre: "Muro 3", tipo: "muro", cantidad: 1, desc: "east side Berlin", precio: 500, tamaño: "2x3", img: './img/muro.jpg'},
    {id: 10, nombre: "Muro 4", tipo: "muro", cantidad: 1, desc: "east side Berlin", precio: 700, tamaño: "2x3", img: './img/muro.jpg'},
    {id: 11, nombre: "Muro 5", tipo: "muro", cantidad: 1,desc: "east side Berlin", precio: 700, tamaño: "4x3", img: './img/muro.jpg'},
    {id: 12, nombre: "Muro 6", tipo: "muro", cantidad: 1, desc: "east side Berlin", precio: 700, tamaño: "4x3", img: './img/muro.jpg'},
    {id: 13, nombre: "Alex 1", tipo: "alex", cantidad: 1, desc: "Alexanderplatz", precio: 900, tamaño: "1x1", img: './img/alex.jpg'},
    {id: 14, nombre: "Alex 2", tipo: "alex", cantidad: 1, desc: "Alexanderplatz", precio: 1400, tamaño: "4x3", img: './img/alex.jpg'},
    {id: 15, nombre: "Alex 3", tipo: "alex", cantidad: 1, desc: "Alexanderplatz", precio: 7000, tamaño: "1x1", img: './img/alex.jpg'},
    {id: 16, nombre: "Alex 4", tipo: "alex", cantidad: 1, desc: "Alexanderplatz", precio: 777, tamaño: "4x3", img: './img/alex.jpg'},
    {id: 17, nombre: "Alex 5", tipo: "alex", cantidad: 1, desc: "Alexanderplatz", precio: 234, tamaño: "4x3", img: './img/alex.jpg'},
    {id: 18, nombre: "Alex 6", tipo: "alex", cantidad: 1, desc: "Alexanderplatz", precio: 1500, tamaño: "2x3", img: './img/alex.jpg'},
    {id: 19, nombre: "Steyr 1", tipo: "steyr", cantidad: 1, desc: "steyr", precio: 1600, tamaño: "1x1", img: './img/steyr.jpg'},
    {id: 20, nombre: "Steyr 2", tipo: "steyr", cantidad: 1, desc: "steyr", precio: 3200, tamaño: "1x1", img: './img/steyr.jpg'},
    {id: 21, nombre: "Steyr 3", tipo: "steyr", cantidad: 1, desc: "steyr", precio: 2300, tamaño: "2x3", img: './img/steyr.jpg'},
    {id: 22, nombre: "Steyr 4", tipo: "steyr", cantidad: 1, desc: "steyr", precio: 5600, tamaño: "2x3", img: './img/steyr.jpg'},
    {id: 23, nombre: "Steyr 5", tipo: "steyr", cantidad: 1, desc: "steyr", precio: 1700, tamaño: "4x3", img: './img/steyr.jpg'},
    {id: 24, nombre: "Steyr 6", tipo: "steyr", cantidad: 1, desc: "steyr", precio: 800, tamaño: "4x3", img: './img/steyr.jpg'},
]